/**
 * Hand-written stand-in for a file normally generated by `openapi-typescript`
 * from a real backend's OpenAPI spec. Shaped the same way so swapping in a
 * real generated schema later is a drop-in change.
 */
export interface paths {
  '/me': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              username: string
              role: string
              authenticatedVia: 'basic'
            }
          }
        }
        401: {
          content: {
            'application/json': {
              message: string
            }
          }
        }
      }
    }
  }
  '/digest/me': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              username: string
              role: string
              authenticatedVia: 'digest'
            }
          }
        }
        401: {
          content: {
            'application/json': {
              message: string
            }
          }
        }
      }
    }
  }
}
